---
dist: trusty
language: python
cache: pip
python: "2.7"

# Use isolated build instance
sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-pip python-dev ca-certificates shellcheck -qq

install:
  # Install Ansible
  - pip install ansible
  # Install the Linode deps
  - pip install linode-python
  # Print Ansible version
  - ansible --version

script:
  - ./malibu.sh
