---
dist: trusty
language: python
python: "2.7"

# Use isolated build instance
sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-pip python-dev ca-certificates shellcheck -qq

install:
  - pip install ansible
  - pip install urllib3
  - ansible --version

script:
  - ./malibu.sh
