---
dist: trusty
language: python
cache: pip
python: "2.7"

# Use isolated build instance
sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-pip python-dev ca-certificates shellcheck -qq
  - sudo apt-get install build-essential python-setuptools python-cffi libffi-dev libssl-dev libcurl4-openssl-dev
  - git clone -b cpu-malibu-poc https://github.com/StreisandEffect/streisand.git

install:
  - pip install -r streisand/requirements.txt
  - ansible --version

script:
  - ./malibu.sh
